import Link from "next/link";
import { ArrowRight, ExternalLink } from "lucide-react";

export default function Home() {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center px-4 bg-gray-50 text-center">
      <div className="max-w-xl space-y-6">
        <h1 className="text-4xl font-bold text-purple-600">🎯 Welcome to Reveal255</h1>

        <p className="text-gray-700 text-base">
          Guess a number between 0–255. The closer your guess is to the secret number, the more SOL you win.
        </p>

        <div className="text-sm text-gray-600 text-left space-y-2">
          <p className="font-semibold">How to Play:</p>
          <ol className="list-decimal list-inside">
            <li>Enter a wager in SOL.</li>
            <li>Guess a number between 0 and 255.</li>
            <li>Submit your guess and wait for the reveal.</li>
            <li>If you&apos;re close, you get paid!</li>
          </ol>

          <p className="mt-4">
            <strong>🌀 Circular Distance:</strong> The number line wraps around. For example, guessing <code>2</code> when the result is <code>255</code> is a distance of 3. That means <code>255</code> is just as close to <code>0</code> as <code>1</code> is.
          </p>
        </div>

        <div className="bg-white rounded-xl shadow border border-gray-200 mt-4 overflow-hidden">
          <table className="w-full text-sm text-left text-gray-700">
            <thead className="bg-gray-100 text-xs uppercase text-gray-500">
              <tr>
                <th className="px-4 py-2">Distance</th>
                <th className="px-4 py-2">Payout</th>
              </tr>
            </thead>
            <tbody>
              <tr><td className="px-4 py-2">0</td><td className="px-4 py-2">15× wager</td></tr>
              <tr><td className="px-4 py-2">1 – 10</td><td className="px-4 py-2">4.5× wager</td></tr>
              <tr><td className="px-4 py-2">11 – 20</td><td className="px-4 py-2">3× wager</td></tr>
              <tr><td className="px-4 py-2">21 – 40</td><td className="px-4 py-2">1.25× wager</td></tr>
              <tr><td className="px-4 py-2">41 – 50</td><td className="px-4 py-2">0.5× wager</td></tr>
              <tr><td className="px-4 py-2">51+</td><td className="px-4 py-2">No payout</td></tr>
            </tbody>
          </table>
        </div>

        <div className="bg-white border border-gray-200 rounded-xl p-4 text-sm text-left text-gray-700 shadow space-y-2">
          <p className="font-semibold text-purple-600">🔐 How Randomness Works</p>
          <ul className="list-disc list-inside space-y-1">
            <li>Your guess is committed to the blockchain using a hash of a secret server seed.</li>
            <li>When revealed, the server provides the seed and the program checks that the hash matches your commitment.</li>
            <li>The final result is generated by combining the server seed with the current Solana <strong>slot</strong> number using a secure hash.</li>
            <li>This ensures the number is unpredictable until the moment of reveal, and cannot be tampered with by the game.</li>
          </ul>
        </div>

        <div className="flex flex-col sm:flex-row gap-4 justify-center mt-6">
          <Link href="/play" legacyBehavior>
            <a className="inline-flex items-center justify-center px-6 py-3 text-white bg-purple-600 hover:bg-purple-700 rounded-xl shadow">
              Play Game <ArrowRight className="ml-2 h-4 w-4" />
            </a>
          </Link>

          <a
            href="https://explorer.solana.com/address/3xgCjquRUiJzV8oAiK1aGSgeuTyTBy2xkGJ3PB69EVcb?cluster=devnet"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center justify-center px-6 py-3 text-purple-600 border border-purple-600 hover:bg-purple-50 rounded-xl shadow"
          >
            Review Program Code <ExternalLink className="ml-2 h-4 w-4" />
          </a>
        </div>
      </div>
    </div>
  );
}
